version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - .env  # Chỉ định tệp .env mà Docker sẽ sử dụng
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/mydb
    depends_on:
      - mongo
    restart: unless-stopped
    working_dir: /app
    command: node server.js

  frontend:
    build:
      context: ./solution
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  mongo-data:
